export const MOVIE_FETCH_DETAIL_REQUEST =
  "movieDetail/MOVIE_FETCH_DETAIL_REQUEST";
export const MOVIE_FETCH_DETAIL_SUCCESS =
  "movieDetail/MOVIE_FETCH_MOVIES_SUCCESS";
export const MOVIE_FETCH_DETAIL_FAILED =
  "movieDetail/MOVIE_FETCH_MOVIES_FAILED";
